version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lab1_postgres
    environment:
      POSTGRES_DB: bigdata_lab1
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
      - ./исходные\ данные:/data
    restart: unless-stopped

volumes:
  postgres_data:
